### ISSUE TITLE
publish to pypi pip index 

### ISSUE THREAD

**Issue by shadowbq** [opendxl/opendxl-client-python#1]
Can the opendxl project claim the name space and publish dxlclient to pypi

PyPI - the Python Package Index
https://pypi.python.org/pypi?%3Aaction=search&term=dxlclient&submit=search

**Comment by chrissmith-mcafee** [comment]
Thanks for reporting this. 

We have obtained the "dxlclient" name space on PyPI and from this point forward we will publish our releases there:
https://pypi.python.org/pypi?:action=display&name=dxlclient
