### ISSUE TITLE
python 3 support

### ISSUE THREAD

**Issue by antoinebouchard** [opendxl/opendxl-client-python#10]
Noticed a lot of dependencies on python2 (e.g print statement, except, ...) - gave me some headaches trying to modify the code for python3 until I sucked it up and installed python2 to get the client to run.

Should at min document python2 required

**Comment by vkrish-mcafee** [comment]
Hi
Sorry for the trouble you encountered with using the client.  It does say that 2.7.8+ is required and Python3 is not supported. It is buried in the doc at
https://opendxl.github.io/opendxl-client-python/pydoc/installation.html.
We will modify it to be more obvious
Thanks
Viji

**Comment by necrose99** [comment]
C:\Users\A660707\Downloads\opendxl-client-python-master>py -3.6  setup.py build
--plat-name=win-amd64 bdist_wheel >> C:\Users\A660707\Downloads\opendxl-client-p
ython-master\3.6-log.txt
Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    VERSION = __import__('dxlclient').get_product_version()
  File "C:\Users\A660707\Downloads\opendxl-client-python-master\dxlclient\__init
__.py", line 114, in <module>
    from dxlclient.broker import *
  File "C:\Users\A660707\Downloads\opendxl-client-python-master\dxlclient\broker
.py", line 223
    except socket.error, msg:
                       ^
SyntaxError: invalid syntax

C:\Users\A660707\Downloads\opendxl-client-python-master>py -3.6  setup.py build
--plat-name=win-amd64 bdist_wheel &>> C:\Users\A660707\Downloads\opendxl-client-
python-master\3.6-log.txt
The syntax of the command is incorrect.

C:\Users\A660707\Downloads\opendxl-client-python-master>py -3.6  setup.py build
--plat-name=win-amd64 bdist_wheel

**Comment by necrose99** [comment]
[dxlclient-3.1.0.586-py2.7.zip](https://github.com/opendxl/opendxl-client-python/files/1170503/dxlclient-3.1.0.586-py2.7.zip)
MSI wheel egg, etc builds fin under 2.7.x  3.x however would prove more useful , with [winpython](https://winpython.github.io/)  so thus nothing is installed..

**Comment by jbarlow-mcafee** [comment]
We've added support for running the client under Python 3 in the 4.1.0.184 and later releases. See the [latest release](https://github.com/opendxl/opendxl-client-python/releases/tag/4.1.0.185) for more details. If you experience any problems using the new release, please file a new issue. I'm closing out this issue.
