### ISSUE TITLE
packaged goodies. 

### ISSUE THREAD

**Issue by necrose99** [opendxl/opendxl-client-python#12]
[Mcafee-DXL.zip](https://github.com/opendxl/opendxl-client-python/files/1191299/Mcafee-DXL.zip)

eggs wheels , ,exe , MSI 

python setup.py build bdist_egg bdist_wininst bdsit_msi  for various Open-dxl related  items 
 (bdist_wheel when possible) on windows ,  bdist_rpm can be cone on linux boxes... 

can add to distributions https://github.com/opendxl/****/releases  if you like.

**Comment by chrissmith-mcafee** [comment]
Thanks for putting this together.

Issues is probably not the best location for this as it typically used for bugs/enhancements for the OpenDXL Client itself. It might make more sense to establish a repository and post your releases there. 

Thanks,
Chris
