### ISSUE TITLE
 provisioning dxl client failure with status: Error 0. Message: For input string: "7684354456"

### ISSUE THREAD

**Issue by sreveliotty** [opendxl/opendxl-client-python#31]
Hello,

I'm trying to provision a Linux client but getting a failure message (below) immediately after generating the client.key.  Any assistance is appreciated.  

Python 2.7.13
'OpenSSL 1.0.2k-fips  26 Jan 2017'
dxlclient          4.1.0.185 
RHEL 7.4
ePO 5.9 

**-bash-4.2$ python -m dxlclient provisionconfig config  x.x.x.x epo-subjectname**

Enter server username:

Enter server password:

INFO: Saving csr file to config/client.csr

INFO: Saving private key file to config/client.key

**ERROR: Command failed. Message: Request to x.x.x.x:8443/DxlBrokerMgmt.generateOpenDXLClientProvisioningPackageCmd failed with status: Error 0. Message: For input string: "7684354456"**

**Comment by jbarlow-mcafee** [comment]
Hi @sreveliotty,

I haven't encountered this problem and am not sure exactly what causes it.

Could you try running the command in verbose mode and provide more of the output, like this?

```
$ python -m dxlclient -vv provisionconfig config [epo-server-host] epo-subjectname
```
This should show payloads for the HTTP requests and responses and a Python stack trace for the failure.  In particular, I'm curious to see the format of the GET request which should be made for the `generateOpenDXLClientProvisioningPackageCmd`. That should look something like this:

```
DEBUG: urllib3.connectionpool: https://x.x.x.x:8443 "GET /remote/DxlBrokerMgmt.generateOpenDXLClientProvisioningPackageCmd?%3Aoutput=json&csrString=-----BEGIN+CERTIFICATE+REQUEST-----%0A...%0A-----END+CERTIFICATE+REQUEST-----%0A HTTP/1.1" 200 5649
```

It would be interesting to try pasting that content into a local with curl or wget request to see if you observe the same failure. For example:

```
curl -u username:password -v "https://[epo-server-host]:8443/remote/DxlBrokerMgmt.generateOpenDXLClientProvisioningPackageCmd%3Aoutput=json&csrString=-----BEGIN+CERTIFICATE+REQUEST-----%0A...%0A-----END+CERTIFICATE+REQUEST-----%0A"
```

If the curl/wget request succeeds but the Python tool fails, the problem may be specific to the Python code, not sure.

---

From the response error message, it seems like the request is getting to the ePO server. Could you see if there are any error messages being written to the ePO `orion.log` file (C:\Program Files (x86)\McAfee\ePolicy Orchestrator\Server\Logs\orion.log) around the time of the failure. These also might provide more insights into the failure.

Also, what version of the DXL-related extensions (in particular, the `McAfee DXL Broker Management` extension) are you using in ePO?

**Comment by sreveliotty** [comment]
Thanks @jbarlow-mcafee :

here's the command with increased verbosity.  curl command below as well - that failed complaining about a self signed cert in the certificate chain unless I used -k 

Only thing I noticed in the orion.log was older messages about not being able to get health status for com.intel.mar.service.client.ServiceException: java.lang.IllegalArgumentException: Illegal URL: /

DXL Broker management extension version is 4.0.0.454

thanks for your help

python -m dxlclient -vv provisionconfig config [epo-server-host] epo-subjectname

Enter server username:
Enter server password:
INFO: dxlclient._cli._crypto: Saving csr file to config/client.csr
INFO: dxlclient._cli._crypto: Saving private key file to config/client.key
DEBUG: dxlclient._cli._management_service: Invoking request https://x.x.x.x:8443/remote/DxlBrokerMgmt.generateOpenDXLClientProvisioningPackageCmd with the following parameters:
DEBUG: dxlclient._cli._management_service: {':output': 'json', 'csrString': '-----BEGIN CERTIFICATE REQUEST-----\nMIICnTCCAYUCAQAwFzEVMBMGA1UEAwwM……——END CERTIFICATE REQUEST-----\n'}
DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): x.x.x.x
DEBUG: urllib3.connectionpool: https://x.x.x.x:8443 "GET /remote/DxlBrokerMgmt.generateOpenDXLClientProvisioningPackageCmd?%3Aoutput=json&csrString=-----BEGIN+CERTIFICATE+REQUEST-----%0AMIICnTCCAYUCAQAwFzEVMBMGA1UEAwwMcnNtY2FmZWVwby0xMIIBIjANBgkqhkiG%0A9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnUovmB5UPjJ8BHl6HvxN3CQccSCXEt%2FPiht3%0A6S9yFLRa5b6iPbBfHJOBKNkEvPQU5zRqY3H%2BWdvMyZ8uztaIgmrcF551Hz7Fp8EP%0A-----END+CERTIFICATE+REQUEST-----%0A HTTP/1.1" 200 43
DEBUG: dxlclient._cli._management_service: Response: Error 0 :
For input string: "7684354456"

ERROR: dxlclient._cli: Command failed. Message: Request to x.x.x.x:8443/DxlBrokerMgmt.generateOpenDXLClientProvisioningPackageCmd failed with status: Error 0. Message: For input string: "7684354456"
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/site-packages/dxlclient/__main__.py", line 11, in <module>
    cli_run()
  File "/usr/local/lib/python2.7/site-packages/dxlclient/_cli/__init__.py", line 110, in cli_run
    parsed_args.func(parsed_args)
  File "/usr/local/lib/python2.7/site-packages/dxlclient/_cli/_cli_subcommands.py", line 625, in execute
    {"csrString": csr_as_string}).split(",")
  File "/usr/local/lib/python2.7/site-packages/dxlclient/_cli/_management_service.py", line 62, in invoke_command
    request_target)
  File "/usr/local/lib/python2.7/site-packages/dxlclient/_cli/_management_service.py", line 122, in _parse_response
    request_target, status.strip(), response_detail))

-----
$ curl -k -u admin:Pass4Admin -v "https://x.x.x.x:8443/remote/DxlBrokerMgmt.generateOpenDXLClientProvisioningPackageCmd?%3Aoutput=json&csrString=-----BEGIN+CERTIFICATE+REQUEST-----%0AMIICnTCCAYUCAQAwFzEVMBMGA1UEAwwMcnNtY2FmZWVwby0xMIIBIjANBgkqhkiG%0A9w0BAQEFAAOCAQ8AMIIBCgKCAnJnEGRK9SfvKM58MQ3th%0AiU7%2FXKHlSL4vxvJYOMj%2FvGypWhPL7rZkLj%xpegRqhri5FeL6f%0A4Q%3D%3D%0A-----END+CERTIFICATE+REQUEST-----%0A"
*   Trying x.x.x.x..
* TCP_NODELAY set
* Connected to x.x.x.x (x.x.x.x) port 8443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Request CERT (13):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-SHA
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: O=McAfee; OU=Orion; CN=RSMCAFEEPO-1
*  start date: Jan  1 00:00:00 1970 GMT
*  expire date: Feb 22 02:20:58 2048 GMT
*  issuer: O=McAfee; OU=Orion; CN=Orion_CA_RSMCAFEEPO-1
*  SSL certificate verify result: self signed certificate in certificate chain (19), continuing anyway.
* Server auth using Basic with user 'xxx'
> GET /remote/DxlBrokerMgmt.generateOpenDXLClientProvisioningPackageCmd?%3Aoutput=json&csrString=-----BEGIN+CERTIFICATE+REQUEST-----%0AMIIK64d6AM%0AqSY4ssfX7uouy4v%2FWr1cys37m0JUJuzP2kG8WBMIXhbBCB2BXxpegRqhri5FeL6f%0A4Q%3D%3D%0A-----END+CERTIFICATE+REQUEST-----%0A HTTP/1.1
> Host: x.x.x.x:8443
> Authorization: Basic YWRtaW46UGFzczRBZG1pbg==
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Cache-Control: no-cache,no-store
< Expires: Thu, 16 Aug 2018 12:53:45 GMT
< Set-Cookie: JSESSIONIDSSO=FDB5A413B8A3ED41E816FF64468CEC1B; Path=/; Secure; HttpOnly
< Set-Cookie: JSESSIONID=9B1BB37B513B8951BBEDFD51E20A16D9.route1; Path=/remote; Secure; HttpOnly
< Pragma: no-cache
< X-Content-Type-Options: nosniff
< Content-Type: text/plain;charset=UTF-8
< Content-Length: 43
< Date: Thu, 16 Aug 2018 12:53:45 GMT
< Server: Undefined
< 
Error 0 :
For input string: "7684354456"
* Connection #0 to host x.x.x.x left intact

**Comment by jbarlow-mcafee** [comment]
Hi @sreveliotty,

Thanks for sending this information along. Just to confirm, are the contents of the `csrString` values in your text intentionally truncated? When used as is, they don't appear to decode to valid CSRs.

Unfortunately, I haven't been able to reproduce the issue that you have described. We've tried to reproduce this on a couple of different VMs with the same OS, OpenSSL, Python, dxlclient, ePO, and ePO DXL Broker Management extension versions that you are using -- with no failures so far. We've tried using `epo-subjectname` verbatim as the CN value for the CSR.

I would like to rule out whether this is a problem in how the CSR is being generated. Would you be comfortable with sharing the full content of a test CSR you have generated which reproduces the issue? As you've probably seen, the tool stores that as a file named `client.csr`.

If not, could you at least try running the following command locally to see if the OpenSSL tool interprets the CSR file as valid?

```
$ openssl req -in client.csr -text
```

Also, I'd like to confirm whether there are any differences in the library versions that the tool is using in your client environment. A `pip list` in my test environment shows this:

```
Package    Version  
---------- ---------
asn1crypto 0.24.0   
certifi    2018.8.13
chardet    3.0.4    
configobj  5.0.6    
dxlclient  4.1.0.185
idna       2.7      
msgpack    0.5.6    
oscrypto   0.19.1   
paho-mqtt  1.3.1    
pip        18.0     
requests   2.19.1   
setuptools 40.0.0   
six        1.11.0   
urllib3    1.23     
wheel      0.31.1   
```

Could you provide this list of versions for your environment - or at least the `oscrypto` and `asn1crypto` libraries since these are used for much of the work done to generate the CSR file?

Thanks.

**Comment by sreveliotty** [comment]
Thanks @jbarlow-mcafee 

I was truncating the csr.  Here's another test below, with the client.csr and output of` pip list`

-bash-4.2$ python -m  dxlclient -vv provisionconfig config x.x.x.x resilient
Enter server username:
Enter server password:
INFO: dxlclient._cli._crypto: Saving csr file to config/client.csr
INFO: dxlclient._cli._crypto: Saving private key file to config/client.key
DEBUG: dxlclient._cli._management_service: Invoking request https://x.x.x.x:8443/remote/DxlBrokerMgmt.generateOpenDXLClientProvisioningPackageCmd with the following parameters:
DEBUG: dxlclient._cli._management_service: {':output': 'json', 'csrString': '-----BEGIN CERTIFICATE REQUEST-----\nMIICmjCCAYICAQAwFDESMBAGA1UEAwwJcmVzaWxpZW50MIIBIjANBgkqhkiG9w0B\nAQEFAAOCAQ8AMIIBCgKCAQEAr1fW4WwXVR4uR2ueJI+g5U2tzk1itTwl5XBTIgYU\n2cG0zOvY64LOFHicPYxjwFseJa9pxOCtC+C12MFpFj+SHSF38PKDt/UrCHap+mVW\n1SWyDw1UaqVXu2ounAHyJIWDW83xQEd0Oy5J3ALZqeATwS4ML25IjiMvsnLX1nco\ne+r/cZ4+GdgBVpb7XlIOqtDWmoj1xMdjRYjV/x3U2mmjri3jcIADxlAFAAf2/pY2\naleZQc8eidNepoXj7Gze+EmZliSJre+2foJOOlmRiEvkliWqwjePYjnygHgnFLtp\nwbUhIsBbUNFqVXT061soTzNRpZ4LwSQefotQbyj6XhVxhQIDAQABoEEwPwYJKoZI\nhvcNAQkOMTIwMDAJBgNVHRMEAjAAMA4GA1UdDwEB/wQEAwIFoDATBgNVHSUEDDAK\nBggrBgEFBQcDAjANBgkqhkiG9w0BAQsFAAOCAQEAdoOEbqngDQOqonYXxJcA1z4i\n098iUxi1zddp4lFus1XUPhKsxT9GeA9d2pBFtwNteMDeyIYEOcFFqMHKuWqEFUqi\nWtB+eNnxK5/fd4unYBH7uNBXGDDND7CdFDR4wIWKHyV/rA/m3JEUTQS+Khou/d1+\nYDvZcXsTvmBuuLugOEDCGjEAhWGaQ4yV3r74wPB419ZKNNSNW3xsRmOzTdBfDCWV\nrJuWA68qP/9pVQuR0g7z6694NF1axre9jppvYHAJtZ1ymCtDnqbHa7vKnQ4JIoya\nxMazvVSJsG9FjuxJKt7nkSRoU02QsxXVESvjyeNrMhDsVdT8Vc31FEqnF+cVWg==\n-----END CERTIFICATE REQUEST-----\n'}
DEBUG: urllib3.connectionpool: Starting new HTTPS connection (1): x.x.x.x
DEBUG: urllib3.connectionpool: https://x.x.x.x:8443 "GET /remote/DxlBrokerMgmt.generateOpenDXLClientProvisioningPackageCmd?%3Aoutput=json&csrString=-----BEGIN+CERTIFICATE+REQUEST-----%0AMIICmjCCAYICAQAwFDESMBAGA1UEAwwJcmVzaWxpZW50MIIBIjANBgkqhkiG9w0B%0AAQEFAAOCAQ8AMIIBCgKCAQEAr1fW4WwXVR4uR2ueJI%2Bg5U2tzk1itTwl5XBTIgYU%0A2cG0zOvY64LOFHicPYxjwFseJa9pxOCtC%2BC12MFpFj%2BSHSF38PKDt%2FUrCHap%2BmVW%0A1SWyDw1UaqVXu2ounAHyJIWDW83xQEd0Oy5J3ALZqeATwS4ML25IjiMvsnLX1nco%0Ae%2Br%2FcZ4%2BGdgBVpb7XlIOqtDWmoj1xMdjRYjV%2Fx3U2mmjri3jcIADxlAFAAf2%2FpY2%0AaleZQc8eidNepoXj7Gze%2BEmZliSJre%2B2foJOOlmRiEvkliWqwjePYjnygHgnFLtp%0AwbUhIsBbUNFqVXT061soTzNRpZ4LwSQefotQbyj6XhVxhQIDAQABoEEwPwYJKoZI%0AhvcNAQkOMTIwMDAJBgNVHRMEAjAAMA4GA1UdDwEB%2FwQEAwIFoDATBgNVHSUEDDAK%0ABggrBgEFBQcDAjANBgkqhkiG9w0BAQsFAAOCAQEAdoOEbqngDQOqonYXxJcA1z4i%0A098iUxi1zddp4lFus1XUPhKsxT9GeA9d2pBFtwNteMDeyIYEOcFFqMHKuWqEFUqi%0AWtB%2BeNnxK5%2Ffd4unYBH7uNBXGDDND7CdFDR4wIWKHyV%2FrA%2Fm3JEUTQS%2BKhou%2Fd1%2B%0AYDvZcXsTvmBuuLugOEDCGjEAhWGaQ4yV3r74wPB419ZKNNSNW3xsRmOzTdBfDCWV%0ArJuWA68qP%2F9pVQuR0g7z6694NF1axre9jppvYHAJtZ1ymCtDnqbHa7vKnQ4JIoya%0AxMazvVSJsG9FjuxJKt7nkSRoU02QsxXVESvjyeNrMhDsVdT8Vc31FEqnF%2BcVWg%3D%3D%0A-----END+CERTIFICATE+REQUEST-----%0A HTTP/1.1" 200 43
DEBUG: dxlclient._cli._management_service: Response: Error 0 :
For input string: "7684354456"

ERROR: dxlclient._cli: Command failed. Message: Request to x.x.x.x:8443/DxlBrokerMgmt.generateOpenDXLClientProvisioningPackageCmd failed with status: Error 0. Message: For input string: "7684354456"
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "build/bdist.linux-x86_64/egg/dxlclient/__main__.py", line 11, in <module>
  File "build/bdist.linux-x86_64/egg/dxlclient/_cli/__init__.py", line 110, in cli_run
  File "build/bdist.linux-x86_64/egg/dxlclient/_cli/_cli_subcommands.py", line 625, in execute
  File "build/bdist.linux-x86_64/egg/dxlclient/_cli/_management_service.py", line 62, in invoke_command
  File "build/bdist.linux-x86_64/egg/dxlclient/_cli/_management_service.py", line 122, in _parse_response
Exception: Request to x.x.x.x:8443/DxlBrokerMgmt.generateOpenDXLClientProvisioningPackageCmd failed with status: Error 0. Message: For input string: "7684354456"



```

-----BEGIN CERTIFICATE REQUEST-----
MIICmjCCAYICAQAwFDESMBAGA1UEAwwJcmVzaWxpZW50MIIBIjANBgkqhkiG9w0B
AQEFAAOCAQ8AMIIBCgKCAQEAr1fW4WwXVR4uR2ueJI+g5U2tzk1itTwl5XBTIgYU
2cG0zOvY64LOFHicPYxjwFseJa9pxOCtC+C12MFpFj+SHSF38PKDt/UrCHap+mVW
1SWyDw1UaqVXu2ounAHyJIWDW83xQEd0Oy5J3ALZqeATwS4ML25IjiMvsnLX1nco
e+r/cZ4+GdgBVpb7XlIOqtDWmoj1xMdjRYjV/x3U2mmjri3jcIADxlAFAAf2/pY2
aleZQc8eidNepoXj7Gze+EmZliSJre+2foJOOlmRiEvkliWqwjePYjnygHgnFLtp
wbUhIsBbUNFqVXT061soTzNRpZ4LwSQefotQbyj6XhVxhQIDAQABoEEwPwYJKoZI
hvcNAQkOMTIwMDAJBgNVHRMEAjAAMA4GA1UdDwEB/wQEAwIFoDATBgNVHSUEDDAK
BggrBgEFBQcDAjANBgkqhkiG9w0BAQsFAAOCAQEAdoOEbqngDQOqonYXxJcA1z4i
098iUxi1zddp4lFus1XUPhKsxT9GeA9d2pBFtwNteMDeyIYEOcFFqMHKuWqEFUqi
WtB+eNnxK5/fd4unYBH7uNBXGDDND7CdFDR4wIWKHyV/rA/m3JEUTQS+Khou/d1+
YDvZcXsTvmBuuLugOEDCGjEAhWGaQ4yV3r74wPB419ZKNNSNW3xsRmOzTdBfDCWV
rJuWA68qP/9pVQuR0g7z6694NF1axre9jppvYHAJtZ1ymCtDnqbHa7vKnQ4JIoya
xMazvVSJsG9FjuxJKt7nkSRoU02QsxXVESvjyeNrMhDsVdT8Vc31FEqnF+cVWg==
-----END CERTIFICATE REQUEST-----
```
```

Package            Version    
------------------ -----------
asn1crypto         0.24.0     
cachetools         2.0.1      
certifi            2017.7.27.1
chardet            3.0.4      
circuits           3.2        
configobj          5.0.6      
configparser       3.5.0      
dxlclient          4.1.0.185  
filelock           2.0.12     
idna               2.6        
Jinja2             2.9.6      
keyring            9.1        
MarkupSafe         1.0        
meld3              1.0.2      
msgpack            0.5.6      
oscrypto           0.19.1     
paho-mqtt          1.3.1      
pbr                3.1.1      
pip                18.0       
py                 1.4.33     
PySocks            1.6.7      
pytest             3.0.7      
pytz               2017.2     
requests           2.18.4     
requests-mock      1.3.0      
requests-toolbelt  0.8.0      
resilient          30.0.89    
resilient-circuits 30.0.89    
setuptools         40.0.0     
six                1.10.0     
stomp.py           4.1.18     
stompest           2.3.0      
supervisor         3.0        
urllib3            1.22       
wheel              0.30.0   

```

**Comment by jbarlow-mcafee** [comment]
Thanks, @sreveliotty.

The CSR that you uploaded appears to be valid. When I try the curl request to the `generateOpenDXLClientProvisioningPackageCmd` endpoint on my ePO server, I get a successful response with certificates rather than the "For input string..." error that you are seeing.

For example:

```
OK:                                                                                             
"-----BEGIN CERTIFICATE-----\r\nMIIDVTCCA...
```

To help rule out whether this is a problem with the routing of the HTTP request as opposed to something about the content of the CSR file itself, could you try generating a certificate with the CSR via the ePO web application?

To do that, you could do the following:

1. Sign in to the ePO server in a web browser.
1. Navigate to **Configuration -> Server Settings -> DXL Certificates (ePO Managed)**.
1. In the lower-right corner of the screen, press the `Edit` button.
1. To the right of the `ePO Managed Client Certificates` box, click on the `Import CSR` button.
1. In the `Import Certificate Signing Request` popup, click on the `Browse..` button and select the `client.csr` file that you had previously generated using the Python client's provisionconfig command.
1. Press the `OK` button.

If the certificate could be generated successfully, the `Import` dialog should clear and a new item for the certificate should appear in the `ePO Managed Client Certificates` list box.

If you see an error message on the UI, can you paste in the contents of that message?

Thanks.

**Comment by jbarlow-mcafee** [comment]
Hi @sreveliotty.

One other experiment which would be interesting is to see if the HTTP request works properly if you perform it from a web browser from the ePO server itself. For example, in a local Internet Explorer browser on the ePO server, you could paste the following into the address bar:

```
https://127.0.0.1:8443//remote/DxlBrokerMgmt.generateOpenDXLClientProvisioningPackageCmd?%3Aoutput=json&csrString=-----BEGIN+CERTIFICATE+REQUEST-----%0AMIICmjCCAYICAQAwFDESMBAGA1UEAwwJcmVzaWxpZW50MIIBIjANBgkqhkiG9w0B%0AAQEFAAOCAQ8AMIIBCgKCAQEAr1fW4WwXVR4uR2ueJI%2Bg5U2tzk1itTwl5XBTIgYU%0A2cG0zOvY64LOFHicPYxjwFseJa9pxOCtC%2BC12MFpFj%2BSHSF38PKDt%2FUrCHap%2BmVW%0A1SWyDw1UaqVXu2ounAHyJIWDW83xQEd0Oy5J3ALZqeATwS4ML25IjiMvsnLX1nco%0Ae%2Br%2FcZ4%2BGdgBVpb7XlIOqtDWmoj1xMdjRYjV%2Fx3U2mmjri3jcIADxlAFAAf2%2FpY2%0AaleZQc8eidNepoXj7Gze%2BEmZliSJre%2B2foJOOlmRiEvkliWqwjePYjnygHgnFLtp%0AwbUhIsBbUNFqVXT061soTzNRpZ4LwSQefotQbyj6XhVxhQIDAQABoEEwPwYJKoZI%0AhvcNAQkOMTIwMDAJBgNVHRMEAjAAMA4GA1UdDwEB%2FwQEAwIFoDATBgNVHSUEDDAK%0ABggrBgEFBQcDAjANBgkqhkiG9w0BAQsFAAOCAQEAdoOEbqngDQOqonYXxJcA1z4i%0A098iUxi1zddp4lFus1XUPhKsxT9GeA9d2pBFtwNteMDeyIYEOcFFqMHKuWqEFUqi%0AWtB%2BeNnxK5%2Ffd4unYBH7uNBXGDDND7CdFDR4wIWKHyV%2FrA%2Fm3JEUTQS%2BKhou%2Fd1%2B%0AYDvZcXsTvmBuuLugOEDCGjEAhWGaQ4yV3r74wPB419ZKNNSNW3xsRmOzTdBfDCWV%0ArJuWA68qP%2F9pVQuR0g7z6694NF1axre9jppvYHAJtZ1ymCtDnqbHa7vKnQ4JIoya%0AxMazvVSJsG9FjuxJKt7nkSRoU02QsxXVESvjyeNrMhDsVdT8Vc31FEqnF%2BcVWg%3D%3D%0A-----END+CERTIFICATE+REQUEST-----%0A
```

This should result in a prompt being displayed for the username and password of the ePO administrative user. After entering the proper credentials, the browser should display something like the following if the request is successful:

```
OK:
"-----BEGIN CERTIFICATE-----\r\nMII...
```

If the web browser request is successful, I would wonder if the issue has something to do with how the HTTP request is being routed through the network when run from the command line of the Python client system.

Thanks.

**Comment by sreveliotty** [comment]
Thanks again @jbarlow-mcafee,

I tried importing the client.csr on ePO but it just hung for hours with "Loading..."

When trying to test the HTTP request locally on ePO itself in a browser I'm prompted for credentials and then the page loads:

`Error 0 : For input string: "7684354456"`

(the same error I get from the cli)

**Comment by jbarlow-mcafee** [comment]
Hi @sreveliotty,

Thanks for running these tests.

Another thing that you might try at this point is adding the following block to the `C:\Program Files (x86)\McAfee\ePolicy Orchestrator\Server\conf\orion\log-config.xml` file on the ePO server:

```xml
<logger name="com.mcafee.dxl">
    <level value="debug"/>
</logger>
```

This should result in logging more data during the attempted DXL provisioning operation. You may need to wait a few minutes or restart your ePO server in order for the additional logging to start taking effect.
In the `C:\Program Files (x86)\McAfee\ePolicy Orchestrator\Server\Logs\orion.log` file, you may now start seeing log statements with `util.DxlCertificateUtils` in the line, like this:

```
2018-08-17 10:40:14,911 ERROR [http-nio-8443-exec-22] util.DxlCertificateUtils  - Could not verify certificate request:  Could not convert CSR to PEM format
```

The above line is what I see when sending an intentionally bad CSR file in the curl request, for example.

I would be curious as well to hear if you are running your ePO server in FIPS or non-FIPS mode. (All of my testing has been done with an ePO server in non-FIPS mode).

---

Since you can reproduce the issue by attempting to issue the certificate via the ePO web UI directly, I suspect at this point that this issue more likely lies in the ePO / DXL extension stack than in the OpenDXL Python client. You might have better luck raising the issue through McAfee product support for ePO...

**Comment by sreveliotty** [comment]
@jbarlow-mcafee 
I agree this seems more likely an issue with something in ePO than the DXL client.  I'll continue to look at that side and really appreciate all the help!  Thank you
