### ISSUE TITLE
Needs python 3.x compatibility

### ISSUE THREAD

**Issue by coverband** [opendxl/opendxl-client-python#5]
Tried installing dxlclient-3.0.1.170 via pip on Windows for a 32-bit Python 3.5 environment. It failed with "invalid syntax" on broker.py, line 223.

**Comment by jbarlow-mcafee** [comment]
We've added support for running the client under Python 3 in the 4.1.0.184 and later releases. See the [latest release](https://github.com/opendxl/opendxl-client-python/releases/tag/4.1.0.185) for more details. If you experience any problems using the new release, please file a new issue. I'm closing out this issue.
