### ISSUE TITLE
couldn't startup dxlclient in python 3.9

### ISSUE THREAD

**Issue by freedai** [opendxl/opendxl-client-python#52]
dxlclient failed to startup when we used python:3-slim image which is in python 3.9.

Oct 22 16:14:46 localhost journal:  File "/usr/local/lib/python3.9/site-packages/dxlbootstrap/app.py", line 268, in run
Oct 22 16:14:46 localhost journal:    self._dxl_connect()
Oct 22 16:14:46 localhost journal:  File "/usr/local/lib/python3.9/site-packages/dxlbootstrap/app.py", line 246, in _dxl_connect
Oct 22 16:14:46 localhost journal:    self._dxl_client.connect()
Oct 22 16:14:46 localhost journal:  File "/usr/local/lib/python3.9/site-packages/dxlclient/client.py", line 502, in connect
Oct 22 16:14:46 localhost journal:    while self._thread.isAlive():
Oct 22 16:14:46 localhost journal: AttributeError: 'Thread' object has no attribute 'isAlive'

**Comment by vkrish-mcafee** [comment]
Thanks for reporting the issue. We will take a look at it.

Thanks,
Viji

**Comment by tirkarthi** [comment]
I have created https://github.com/opendxl/opendxl-client-python/pull/53 to fix this. It's due to `isAlive` being deprecated and removed in favour `is_alive`. `is_alive` is present in Python 2 and 3 so it's compatible with both.
