### ISSUE TITLE
John Mcafee Is A Terrible Person

### ISSUE THREAD

**Issue by fehe1755** [opendxl/opendxl-client-python#57]
I wanted to report a problem to Mcafee about their disregard of the heinous, murderous acts of their founder, John Mcafee. In two separate instances, Mcafee has been directly responsible for the deaths and murders of people near him. Instead of doing the "right" thing and owning up to his actions, he instead evaded court and refused to pay his court fees. In one particular instance, he was responsible for a plane crashing and killing the people inside. When the families of the victims sued Mcafee and won, he still refused to pay the 20 odd million in damages. Instead of paying the monetary respect, he instead took to Twitter and claimed that he was a victim of a scheme meant to bring down America's wealthiest individuals. This man is terrible and does not deserve the fame and fortune he has accumulated. Please uninstall Mcafee and do what you can to no longer support this company.

**Comment by Yabbo** [comment]
For as much information as you have you some how failed to realize.

The company was incorporated in Delaware in 1992, and McAfee resigned from the company in 1994. Two years after McAfee Associates went public, McAfee sold his remaining stake in the company.
