### ISSUE TITLE
Client does not know its identity

### ISSUE THREAD

**Issue by lookpl** [opendxl/opendxl-client-python#8]
Dxlclient._config._client_id is generated or taken from config file at start. It can not be used in communication neither as message.source_id (for checking sender) nor event.client_ids (for limiting recipient) as these are different values, unreachable directly from client's code.

**Comment by chrissmith-mcafee** [comment]
Identifiers for OpenDXL clients are assigned by the broker (any value specified by the client is ignored).

However, any valid response coming from the broker will include the client identifier. The following sample code extracts the client's identifier from a broker response (as it was assigned by the broker). In this particular case, we are attempting to invoke a service that does not exist. Even though the service does not exist, the response sent by the broker will contain the client's identifier. In a future version of the client, a convenience method will be exposed which will determine the identifier.

```
    req = Request("/service/does/not/exist")
    res = client.sync_request(req)
    client_id = res.client_ids[0]
```
