### ISSUE TITLE
Dependency on ePO Broker

### ISSUE THREAD

**Issue by nicolas314** [opendxl/opendxl-client-python#9]
Seems the provided samples cannot run without having an instance of ePO Broker:
https://opendxl.github.io/opendxl-client-python/pydoc/epobrokerlistexport.html
Is there any procedure to generate a valid broker list without having to own and run an ePO instance? Having a complete (service + client) runnable demo would be quite helpful.
Thanks!

**Comment by vkrish-mcafee** [comment]
At this time you need to have an ePO instance for configuration. We are working on efforts to address this.

Thanks
Viji

**Comment by nicolas314** [comment]
Ok. Help me help you then: the PKI part can be worked out with openssl, but what about the unique ID stuff? Is it enough to have just UUIDs or do they need to satisfy some properties? I could not find anything in the docs beyond exporting them from ePO. Any pointers appreciated.
Thanks
Nicolas

**Comment by vkrish-mcafee** [comment]
The ids in your properties file have to be unique and they do not need to match the actual broker id. 
Ex <id>=<id>;8883;mybroker.mcafee.com;192.168.1.12.
You can look at the documentation [here ](https://opendxl.github.io/opendxl-client-python/pydoc/dxlclient.client_config.html#dxlclient.client_config.DxlClientConfig.create_dxl_config_from_file) for more info.

Thanks
Viji

**Comment by vkrish-mcafee** [comment]
Updated property broker list format
``
Ex <uuid>=<uuid>;8883;mybroker.mcafee.com;192.168.1.12.
``

Thanks
Viji

**Comment by nicolas314** [comment]
Ok, thanks! Will try and report if I can't work it out.
Thanks again for your fast answers!

**Comment by chrissmith-mcafee** [comment]
An OpenDXL Broker has been released, so an ePO managed broker is no longer required for running the samples.

[OpenDXL Broker](https://github.com/opendxl/opendxl-broker/releases/latest)

Thanks,
Chris
